version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:18.04"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing clang and cmake
          command: 'apt-get update && apt-get install -y build-essential clang-6.0 cmake git libssl-dev zlib1g-dev libuv1-dev'
      - run:
          name: Install deps
          command: './install-ubuntu.sh'
      - run:
          name: Build
          command: 'mkdir build && cd build && cmake .. && make'
